version: '3'

services:

  api:
    build:
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"

  client:
    build:
      context: ./client
    stdin_open: true
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
