// WS

export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const SOCKET_DISCONNECT = 'SOCKET_DISCONECT';
export const SET_SOCKET = 'SET_SOCKET';


// CHANNELS

export const ADD_CHANNEL = 'ADD_CHANNEL';
export const SET_ACTIVE_CHANNEL = 'SET_ACTIVE_CHANNEL';


// USERS

export const ADD_USER = 'ADD_USER';


// MESSAGES

export const ADD_MESSAGE = 'ADD_MESSAGE';
